# Generated by Django 2.0.5 on 2018-05-22 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_verification_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verification_email',
            new_name='sent_verification_emails',
        ),
    ]
