# Generated by Django 2.0.5 on 2018-06-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180522_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accepted_terms',
        ),
    ]
