# Generated by Django 2.0.5 on 2018-06-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='document_type',
            field=models.PositiveSmallIntegerField(choices=[('', 'Tipo de documento'), (1, 'C.C.'), (2, 'NIT'), (3, 'Otro')], verbose_name='tipo de documento'),
        ),
        migrations.AlterField(
            model_name='building',
            name='initial_period',
            field=models.DateField(blank=True, null=True, verbose_name='periodo inicial'),
        ),
    ]
