# Generated by Django 2.0.5 on 2018-06-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_auto_20180606_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='coefficient',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Coeficiente'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='área (Mts)'),
        ),
    ]
