# Generated by Django 2.0.5 on 2018-06-18 19:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_auto_20180616_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaseholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='apellidos')),
                ('document_type', models.PositiveSmallIntegerField(blank=True, choices=[(100, 'C.C.'), (110, 'C.E.'), (120, 'Pasaporte')], null=True, verbose_name='tipo de documento')),
                ('document_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='número de documento')),
                ('mobile_phone', models.CharField(blank=True, default='', error_messages={'min_length': 'Ingrese al menos %(limit_value)d caracteres, (actualmente tiene %(show_value)d).'}, help_text='Si desea ingresar más de un número celular, estos deben ir separados por coma (,).', max_length=32, validators=[django.core.validators.RegexValidator('^[0-9 ,]*$', message='El dato no es válido, sólo debe ingresar números. Si desea ingresar más de un número celular, estos deben estar separados por coma (,).'), django.core.validators.MinLengthValidator(10)], verbose_name='número celular')),
                ('phone_number', models.CharField(blank=True, error_messages={'min_length': 'El campo "Número telefónico" debe tener al menos %(limit_value)d dígitos (actualmente tiene %(show_value)d).'}, help_text='Si desea ingresar más de un número telefónico, estos deben ir separados por coma (,).', max_length=32, validators=[django.core.validators.RegexValidator('^[0-9 ,]*$', message='El dato no es válido, sólo se permiten números. Si desea ingresar más de un número telefónico, estos deben estar separados por coma (,).'), django.core.validators.MinLengthValidator(6)], verbose_name='número telefónico')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo electrónico')),
            ],
            options={
                'verbose_name': 'arrendatario',
                'verbose_name_plural': 'arrendatarios',
                'ordering': ('last_name',),
            },
        ),
        migrations.RemoveField(
            model_name='unit',
            name='leaseholder_email',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='leaseholder_mobile_phone',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='leaseholder_name',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='leaseholder_phone_number',
        ),
        migrations.AddField(
            model_name='leaseholder',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Unit', verbose_name='unidad'),
        ),
    ]
