# Generated by Django 2.0.5 on 2018-06-19 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_building_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='created_by',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
            preserve_default=False,
        ),
    ]
