# Generated by Django 2.0.5 on 2018-06-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_auto_20180619_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseholder',
            name='document_number',
            field=models.CharField(default=1, max_length=32, verbose_name='número de documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaseholder',
            name='document_type',
            field=models.PositiveSmallIntegerField(choices=[(100, 'C.C.'), (110, 'C.E.'), (120, 'Pasaporte')], default=1, verbose_name='tipo de documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='document_number',
            field=models.CharField(default=1, max_length=32, verbose_name='número de documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='document_type',
            field=models.PositiveSmallIntegerField(choices=[(100, 'C.C.'), (110, 'C.E.'), (120, 'Pasaporte')], default=1, verbose_name='tipo de documento'),
            preserve_default=False,
        ),
    ]
