# Generated by Django 2.0.5 on 2018-06-21 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_auto_20180621_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='número')),
                ('parking_lot_type', models.PositiveSmallIntegerField(choices=[(1, 'Asignado (Arrendado o Temporal por sorteo)'), (2, 'Propio')], verbose_name='tipo de parqueadero')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Unit', verbose_name='unidad')),
            ],
            options={
                'verbose_name': 'parqueadero',
                'verbose_name_plural': 'parqueaderos',
                'ordering': ('number',),
            },
        ),
    ]
