# Generated by Django 2.0.5 on 2018-06-26 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0011_parkinglot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='marca')),
                ('vehicle_type', models.PositiveSmallIntegerField(choices=[('', 'Tipo de vehículo'), (1, 'Carro'), (2, 'Motocicleta'), (3, 'Bicicleta')], verbose_name='tipo de vehículo')),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='placa')),
                ('color', models.CharField(max_length=50, verbose_name='color')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Unit', verbose_name='unidad')),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
                'ordering': ('unit',),
            },
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='parking_lot_type',
            field=models.PositiveSmallIntegerField(choices=[('', 'Tipo de parqueadero'), (1, 'Asignado (Arrendado o Temporal por sorteo)'), (2, 'Propio')], verbose_name='tipo de parqueadero'),
        ),
    ]
