# Generated by Django 2.0.5 on 2018-06-27 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0012_auto_20180626_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domesticworker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='apellidos')),
                ('document_type', models.PositiveSmallIntegerField(choices=[(100, 'C.C.'), (110, 'C.E.'), (120, 'Pasaporte')], verbose_name='tipo de documento')),
                ('document_number', models.CharField(max_length=32, verbose_name='número de documento')),
                ('schedule', models.TextField(blank=True, help_text='Días y horarios en los que va a trabajar.', verbose_name='horario')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Unit', verbose_name='unidad')),
            ],
            options={
                'verbose_name': 'trabajador doméstico',
                'verbose_name_plural': 'trabajadores domésticos',
                'ordering': ('unit',),
            },
        ),
    ]
