# Generated by Django 2.0.5 on 2018-06-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0013_domesticworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseholder',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='arrendatario principal'),
        ),
        migrations.AddField(
            model_name='owner',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='propietario principal'),
        ),
    ]
