# Generated by Django 2.0.5 on 2018-06-29 00:28

import app.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0014_auto_20180626_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(help_text='perro, gato, etc.', max_length=30, verbose_name='tipo de mascota')),
                ('breed', models.CharField(max_length=30, verbose_name='raza')),
                ('name', models.CharField(max_length=30, verbose_name='nombre')),
                ('color', models.CharField(max_length=50, verbose_name='color')),
                ('picture', models.ImageField(blank=True, help_text='150x150', max_length=255, upload_to='', validators=[app.validators.FileSizeValidator(4000)])),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Unit', verbose_name='unidad')),
            ],
            options={
                'verbose_name': 'mascota',
                'verbose_name_plural': 'mascotas',
                'ordering': ('unit',),
            },
        ),
    ]
