# Generated by Django 2.0.5 on 2018-07-06 03:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0017_auto_20180629_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='apellidos')),
                ('mobile_phone', models.CharField(error_messages={'min_length': 'Ingrese al menos %(limit_value)d caracteres, (actualmente tiene %(show_value)d).'}, help_text='Si desea ingresar más de un número celular, estos deben ir separados por coma (,).', max_length=32, validators=[django.core.validators.RegexValidator('^[0-9 ,]*$', message='El dato no es válido, sólo debe ingresar números. Si desea ingresar más de un número celular, estos deben estar separados por coma (,).'), django.core.validators.MinLengthValidator(10)], verbose_name='número celular')),
            ],
            options={
                'verbose_name': 'contacto de emergencia',
                'verbose_name_plural': 'contactos de emergencia',
                'ordering': ('last_name',),
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='apellidos')),
                ('birthdate', models.DateField(verbose_name='fecha de nacimiento')),
                ('document_type', models.PositiveSmallIntegerField(choices=[('', 'Tipo de documento'), (100, 'C.C.'), (110, 'C.E.'), (120, 'Pasaporte'), (130, 'Tarjeta de identidad')], verbose_name='tipo de documento')),
                ('document_number', models.CharField(max_length=32, verbose_name='número de documento')),
                ('mobile_phone', models.CharField(blank=True, default='', error_messages={'min_length': 'Ingrese al menos %(limit_value)d caracteres, (actualmente tiene %(show_value)d).'}, help_text='Si desea ingresar más de un número celular, estos deben ir separados por coma (,).', max_length=32, validators=[django.core.validators.RegexValidator('^[0-9 ,]*$', message='El dato no es válido, sólo debe ingresar números. Si desea ingresar más de un número celular, estos deben estar separados por coma (,).'), django.core.validators.MinLengthValidator(10)], verbose_name='número celular')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Unit', verbose_name='unidad')),
            ],
            options={
                'verbose_name': 'residente',
                'verbose_name_plural': 'residentes',
                'ordering': ('last_name',),
            },
        ),
        migrations.AlterField(
            model_name='domesticworker',
            name='document_type',
            field=models.PositiveSmallIntegerField(choices=[('', 'Tipo de documento'), (100, 'C.C.'), (110, 'C.E.'), (120, 'Pasaporte'), (130, 'Tarjeta de identidad')], verbose_name='tipo de documento'),
        ),
        migrations.AlterField(
            model_name='leaseholder',
            name='document_type',
            field=models.PositiveSmallIntegerField(choices=[('', 'Tipo de documento'), (100, 'C.C.'), (110, 'C.E.'), (120, 'Pasaporte'), (130, 'Tarjeta de identidad')], verbose_name='tipo de documento'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='document_type',
            field=models.PositiveSmallIntegerField(choices=[('', 'Tipo de documento'), (100, 'C.C.'), (110, 'C.E.'), (120, 'Pasaporte'), (130, 'Tarjeta de identidad')], verbose_name='tipo de documento'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='document_type',
            field=models.PositiveSmallIntegerField(choices=[('', 'Tipo de documento'), (100, 'C.C.'), (110, 'C.E.'), (120, 'Pasaporte'), (130, 'Tarjeta de identidad')], verbose_name='tipo de documento'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='relationship',
            field=models.CharField(help_text='Amigo, familiar, etc', max_length=50, verbose_name='parentesco'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Resident', verbose_name='residente'),
        ),
    ]
