# Generated by Django 2.0.5 on 2018-07-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0019_buildingmembership_membership_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingmembership',
            name='is_accountant',
        ),
        migrations.RemoveField(
            model_name='buildingmembership',
            name='is_accounting_assistant',
        ),
        migrations.RemoveField(
            model_name='buildingmembership',
            name='is_administrative_assistant',
        ),
        migrations.RemoveField(
            model_name='buildingmembership',
            name='is_administrator',
        ),
        migrations.RemoveField(
            model_name='buildingmembership',
            name='is_fiscal_reviewer',
        ),
    ]
