# Generated by Django 2.0.5 on 2018-07-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0020_auto_20180709_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingmembership',
            name='membership_type',
            field=models.PositiveSmallIntegerField(choices=[('', 'Tipo de membresía'), (1, 'Administrador'), (2, 'Asistente administrativo'), (3, 'Contador'), (4, 'Asistente contable'), (5, 'Revisor fiscal')], verbose_name='tipo de documento'),
        ),
    ]
