# Generated by Django 2.0.5 on 2018-07-18 20:59

from django.db import migrations


def create_unit_update_objects(apps, schema_editor):
    Unit = apps.get_model('buildings', 'Unit')
    UnitDataUpdate = apps.get_model('buildings', 'UnitDataUpdate')
    for unit in Unit.objects.all():
        UnitDataUpdate.objects.create(
            unit=unit,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0022_unitdataupdate'),
    ]

    operations = [
        migrations.RunPython(create_unit_update_objects),
    ]
