# Generated by Django 2.0.5 on 2018-07-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0025_unitdataupdate_owners_update_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitdataupdate',
            name='created_at',
        ),
        migrations.AddField(
            model_name='unitdataupdate',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
