# Generated by Django 2.0.5 on 2018-07-31 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0026_auto_20180727_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='is_resident',
            field=models.BooleanField(default=False, verbose_name='es residente'),
        ),
    ]
