# Generated by Django 2.0.5 on 2018-07-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0028_auto_20180731_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitdataupdate',
            old_name='activated_at',
            new_name='leaseholders_update_activated_at',
        ),
        migrations.AddField(
            model_name='unitdataupdate',
            name='owners_update_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitdataupdate',
            name='leaseholders_update_key',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='clave actualizar arrendatarios'),
        ),
    ]
