# Generated by Django 2.0.5 on 2018-08-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0029_auto_20180731_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdataupdate',
            name='enable_residents_update',
            field=models.BooleanField(default=False, verbose_name='habilitar actualización de residentes'),
        ),
        migrations.AddField(
            model_name='unitdataupdate',
            name='residents_update_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unitdataupdate',
            name='residents_update_key',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='clave actualizar residentes'),
        ),
    ]
