# Generated by Django 2.0.5 on 2018-08-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0030_auto_20180808_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdataupdate',
            name='residents_update',
            field=models.BooleanField(default=False, verbose_name='información de residentes actualizada'),
        ),
        migrations.AddField(
            model_name='unitdataupdate',
            name='visitors_update',
            field=models.BooleanField(default=False, verbose_name='información de visitantes autorizados actualizada'),
        ),
    ]
