# Generated by Django 2.0.5 on 2018-08-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0031_auto_20180809_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdataupdate',
            name='vehicles_update',
            field=models.BooleanField(default=False, verbose_name='información de vehículos actualizada'),
        ),
    ]
