# Generated by Django 2.0.5 on 2018-08-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0032_unitdataupdate_vehicles_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdataupdate',
            name='domestic_workers_update',
            field=models.BooleanField(default=False, verbose_name='información de trabajadores domésticos actualizada'),
        ),
    ]
