# Generated by Django 2.0.5 on 2018-08-11 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0031_auto_20180809_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_period', models.DateField()),
                ('apply_retention', models.BooleanField(default=False, verbose_name='aplica retención a título de impuesto de renta')),
                ('is_self_withholding', models.BooleanField(default=False, verbose_name='es autorretenedor a título impuesto de renta')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='tarifa')),
                ('nit_dian', models.CharField(max_length=32, unique=True, verbose_name='Nit DIAN')),
                ('local_nit_dian', models.CharField(help_text='Secretaría de hacienda distrital SHD', max_length=32, unique=True, verbose_name='Nit DIAN local')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buildings.Building', verbose_name='unidad')),
            ],
            options={
                'verbose_name': 'contabilidad',
                'verbose_name_plural': 'contabilidades',
                'ordering': ('condo',),
            },
        ),
        migrations.CreateModel(
            name='EconomicActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('code', models.CharField(max_length=10, verbose_name='código')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='tarifa')),
            ],
            options={
                'verbose_name': 'actividad económica',
                'verbose_name_plural': 'actividades aconómicas',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='accounting',
            name='economic_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.EconomicActivity', verbose_name='actividad económica'),
        ),
    ]
