# Generated by Django 2.0.5 on 2018-08-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='initial_period',
            field=models.DateField(verbose_name='periodo inicial'),
        ),
        migrations.AlterField(
            model_name='economicactivity',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
    ]
