# Generated by Django 2.0.5 on 2018-08-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20180812_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='economicactivity',
            options={'ordering': ('code',), 'verbose_name': 'actividad económica', 'verbose_name_plural': 'actividades aconómicas'},
        ),
        migrations.AlterField(
            model_name='economicactivity',
            name='code',
            field=models.IntegerField(verbose_name='código'),
        ),
    ]
