# Generated by Django 2.0.5 on 2018-08-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20180812_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='tarifa'),
        ),
    ]
